name: gpr
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - applaunchservices=0.3.0
  - appnope=0.1.3
  - argh=0.26.2
  - arrow=1.2.2
  - astroid=2.11.5
  - atomicwrites=1.4.0
  - attrs=21.4.0
  - autopep8=1.6.0
  - babel=2.10.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - binaryornot=0.4.4
  - black=22.3.0
  - bleach=5.0.0
  - blosc=1.21.1
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - cartopy=0.18.0
  - certifi=2022.12.7
  - cffi=1.14.6
  - cfitsio=3.470
  - cftime=1.6.0
  - chardet=4.0.0
  - charls=2.1.0
  - charset-normalizer=2.0.12
  - click=8.1.3
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - comm=0.1.2
  - cookiecutter=1.7.3
  - cryptography=36.0.2
  - curl=7.71.1
  - cycler=0.11.0
  - cytoolz=0.11.2
  - dask-core=2022.5.0
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.2.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.3.4
  - docstring-to-markdown=0.11
  - docutils=0.17.1
  - entrypoints=0.4
  - esmf=8.0.1
  - expat=2.2.9
  - flake8=6.0.0
  - fontconfig=2.13.1
  - fonttools=4.33.3
  - freetype=2.10.4
  - freexl=1.0.5
  - fsspec=2022.3.0
  - geos=3.8.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.68.3
  - glib-tools=2.68.3
  - gsl=2.6
  - hdf4=4.2.13
  - hdf5=1.10.6
  - hdfeos2=2.20
  - hdfeos5=5.1.16
  - icu=67.1
  - idna=3.3
  - imagecodecs=2020.5.30
  - imageio=2.13.1
  - imagesize=1.3.0
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.7.1
  - inflection=0.5.1
  - intervaltree=3.0.2
  - ipykernel=6.19.2
  - ipython=7.33.0
  - ipython_genutils=0.2.0
  - isort=5.10.1
  - jasper=1.900.1
  - jedi=0.18.1
  - jellyfish=0.9.0
  - jinja2=3.1.2
  - jinja2-time=0.2.0
  - jpeg=9d
  - json-c=0.13.1
  - jsonschema=4.5.1
  - jupyter_client=7.4.9
  - jupyter_core=4.10.0
  - jupyterlab_pygments=0.2.2
  - jxrlib=1.1
  - kealib=1.4.13
  - keyring=23.4.0
  - kiwisolver=1.4.2
  - krb5=1.17.1
  - lazy-object-proxy=1.7.1
  - lcms2=2.11
  - lerc=2.2.1
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libcxx=14.0.3
  - libdap4=3.20.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgdal=3.1.4
  - libgfortran=4.0.0
  - libgfortran4=7.5.0
  - libglib=2.68.3
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libnetcdf=4.7.4
  - libnghttp2=1.41.0
  - libpng=1.6.37
  - libpq=12.3
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.0
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - libzopfli=1.0.3
  - llvm-openmp=8.0.1
  - locket=1.0.0
  - lz4-c=1.9.2
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - mccabe=0.7.0
  - mistune=0.8.4
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - mysql-common=8.0.22
  - mysql-libs=8.0.22
  - nbclient=0.6.3
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - ncl=6.6.2
  - ncurses=6.2
  - nest-asyncio=1.5.5
  - netcdf-fortran=4.5.3
  - netcdf4=1.5.6
  - networkx=3.0
  - nspr=4.29
  - nss=3.47
  - numpydoc=1.2.1
  - olefile=0.46
  - openjpeg=2.3.1
  - openmp=8.0.1
  - openssl=1.1.1t
  - packaging=23.0
  - pandas=1.4.2
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pathspec=0.9.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pixman=0.40.0
  - platformdirs=2.5.1
  - pluggy=1.0.0
  - poppler=0.89.0
  - poppler-data=0.4.10
  - postgresql=12.3
  - poyo=0.5.0
  - proj=7.1.1
  - prompt-toolkit=3.0.29
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyflakes=3.0.1
  - pygments=2.12.0
  - pylint=2.13.8
  - pylint-venv=3.0.1
  - pyls-spyder=0.4.0
  - pyobjc-core=8.5
  - pyobjc-framework-cocoa=8.5
  - pyobjc-framework-coreservices=8.5
  - pyobjc-framework-fsevents=8.5
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.1
  - pyshp=2.3.0
  - pysocks=1.7.1
  - python=3.9.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python-lsp-black=1.2.1
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.7.1
  - python-lsp-server-base=1.5.0
  - python-slugify=6.1.2
  - python.app=1.4
  - python_abi=3.9
  - pytoolconfig=1.2.5
  - pytz=2022.1
  - pywavelets=1.3.0
  - pyyaml=6.0
  - pyzmq=23.2.1
  - qdarkstyle=3.0.3
  - qstylizer=0.2.2
  - qt=5.12.9
  - qtawesome=1.2.3
  - qtconsole=5.4.0
  - qtconsole-base=5.3.0
  - qtpy=2.1.0
  - readline=8.0
  - requests=2.27.1
  - rope=1.7.0
  - rtree=1.0.0
  - scikit-image=0.19.2
  - shapely=1.7.1
  - six=1.16.0
  - snappy=1.1.9
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sphinx=4.5.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.4.2
  - spyder-kernels=2.4.2
  - sqlite=3.33.0
  - text-unidecode=1.3
  - textdistance=4.2.2
  - three-merge=0.1.1
  - tifffile=2020.12.8
  - tiledb=2.1.2
  - tinycss2=1.1.1
  - tk=8.6.10
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.11.2
  - tornado=6.2
  - traitlets=5.9.0
  - typed-ast=1.5.3
  - typing-extensions=4.2.0
  - typing_extensions=4.2.0
  - tzcode=2020a
  - tzdata=2020d
  - udunits2=2.2.27.6
  - ujson=4.0.2
  - unicodedata2=14.0.0
  - unidecode=1.3.4
  - urllib3=1.26.9
  - watchdog=2.1.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - whatthepatch=1.0.4
  - wheel=0.35.1
  - wrapt=1.14.1
  - wurlitzer=3.0.2
  - xerces-c=3.2.3
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.32.0
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.8.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==1.2.0
    - active-subspaces==0.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arviz==0.16.1
    - astunparse==1.6.3
    - athena-mathlab==0.1.2
    - autograd==1.5
    - bambi==0.13.0
    - cachetools==5.2.0
    - cons==0.4.6
    - cython==0.29.32
    - deprecat==2.1.1
    - deprecated==1.2.13
    - dm-tree==0.1.7
    - et-xmlfile==1.1.0
    - etuples==0.3.9
    - fastprogress==1.0.3
    - filelock==3.13.1
    - flatbuffers==22.9.24
    - formulae==0.5.1
    - future==0.18.2
    - gast==0.4.0
    - google-auth==2.12.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - gpflow==2.6.3
    - gpy==1.10.0
    - gpyopt==1.2.6
    - grpcio==1.49.1
    - h5netcdf==1.3.0
    - h5py==3.7.0
    - ipywidgets==7.7.0
    - joblib==1.2.0
    - jupyter==1.0.0
    - jupyter-console==6.4.3
    - jupyterlab-widgets==1.1.0
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - lark==1.1.3
    - libclang==14.0.6
    - logical-unification==0.4.6
    - markdown==3.4.1
    - minikanren==1.0.3
    - mpmath==1.2.1
    - multipledispatch==0.6.0
    - nltk==3.8.1
    - notebook==6.4.11
    - numpy==1.22.1
    - oauthlib==3.2.1
    - openpyxl==3.0.10
    - opt-einsum==3.3.0
    - paramz==0.9.5
    - patsy==0.5.3
    - pip==23.3.1
    - prometheus-client==0.14.1
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pymc==5.9.2
    - pymc3==3.11.5
    - pytensor==2.17.4
    - python-graphviz==0.20.1
    - regex==2023.6.3
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.2.1
    - scipy==1.11.3
    - seaborn==0.11.2
    - semver==3.0.2
    - send2trash==1.8.0
    - setuptools==68.2.2
    - tabulate==0.9.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.10.0
    - tensorflow-estimator==2.10.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - tensorflow-probability==0.18.0
    - termcolor==2.0.1
    - terminado==0.15.0
    - theano-pymc==1.1.2
    - threadpoolctl==3.1.0
    - torch==1.13.0
    - tqdm==4.65.0
    - werkzeug==2.2.2
    - widgetsnbextension==3.6.0
    - xarray==2022.11.0
    - xarray-einstats==0.6.0
